### ISSUE TITLE
More units

### ISSUE THREAD

**Issue by fabaff** [skymaya/unitconvert#10]
I decided to use that library to do the conversions for the `system_monitoring` component ([#10130](https://github.com/home-assistant/home-assistant/pull/10130)) of [Home Assistant](https://home-assistant.io/).

Those are the needed for sure:

- [ ] Frequency
- [ ] Disk throughput
- [ ] Network speed/bandwidth

I guess more units could be useful, especially physical ones (speed, acceleration, etc.)

**Comment by skymaya** [comment]
Thanks for the feedback - I'll add the units you have requested.

**Comment by fabaff** [comment]
I can add them by myself. I created the issue only to track it.

**Comment by fabaff** [comment]
I will use a different library.

**Comment by tehfink** [comment]
How about area conversions?
